source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'PetAdoption-iOS' do
  pod 'MGBoxKit'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'XLForm'
  pod 'Alamofire', '~> 3.5'
  pod 'AlamofireImage', '~> 2.5'
  pod 'Toast-Swift', '~> 1.3.0'
end
