source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'PetAdoption-iOS' do
  pod 'SDWebImage'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.0'
  pod 'Toast-Swift', '~> 2.0'
end

target 'PetAdoptionTransportKit' do
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.0'
end

