source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'PetAdoption-iOS' do
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SwiftyJSON'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'PetAdoptionTransportKit' do
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SwiftyJSON'
end

